const vars = [
  {
    name: "Spacing",
    id: "spacing",
    data: [
      { name: "--grid-gutter", value: "1rem" },
      { name: "--spacing-xxx-small", value: "0.125rem" },
      { name: "--spacing-xx-small", value: "0.25rem" },
      { name: "--spacing-x-small", value: "0.5rem" },
      { name: "--spacing-small", value: "0.75rem" },
      { name: "--spacing-medium", value: "1rem" },
      { name: "--spacing-large", value: "1.25rem" },
      { name: "--spacing-x-large", value: "1.75rem" },
      { name: "--spacing-xx-large", value: "2.25rem" },
      { name: "--spacing-xxx-large", value: "3rem" },
      { name: "--spacing-xxxx-large", value: "4.5rem" },
    ],
  },
  {
    name: "Colors",
    id: "colors",
    data: [
      { name: "--color-black", value: "#000" },
      { name: "--color-white", value: "#fff" },
      { name: "--color-primary-50", value: "#7dd3fc" },
      { name: "--color-primary-100", value: "#0369a1" },
      { name: "--color-primary-150", value: "#082e45" },
      { name: "--color-primary-text", value: "var(--color-white)" },
      { name: "--color-secondary-50", value: "#e17ddd" },
      { name: "--color-secondary-100", value: "#8e1292" },
      { name: "--color-secondary-150", value: "#3f0e3d" },
      { name: "--color-secondary-text", value: "var(--color-white)" },
    ],
  },
  {
    name: "Borders and Shading",
    id: "borders-and-shading",
    data: [
      { name: "--border-radius-small", value: "0.125rem" },
      { name: "--border-radius-medium", value: "0.25rem" },
      { name: "--border-radius-large", value: "0.5rem" },
      { name: "--border-radius-x-large", value: "1rem" },
      { name: "--border-radius-circle", value: "50%" },
      { name: "--border-radius-pill", value: "9999px" },
      { name: "--shadow-x-small", value: "0 1px 0 #0d131e0d" },
      { name: "--shadow-small", value: "0 1px 2px #0d131e1a" },
      { name: "--shadow-medium", value: "0 2px 4px #0d131e1a" },
      { name: "--shadow-large", value: "0 2px 8px #0d131e1a" },
      { name: "--shadow-x-large", value: "0 4px 16px #0d131e1a" },
    ],
  },
  {
    name: "Transitions",
    id: "transitions",
    data: [
      { name: "--transition-x-slow", value: "1000ms" },
      { name: "--transition-slow", value: "500ms" },
      { name: "--transition-medium", value: "250ms" },
      { name: "--transition-fast", value: "150ms" },
      { name: "--transition-x-fast", value: "50ms" },
    ],
  },
  {
    name: "Fonts",
    id: "fonts",
    data: [
      {
        name: "--font-mono",
        value: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace',
      },
      {
        name: "--font-sans",
        value:
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      },
      { name: "--font-serif", value: 'Georgia, "Times New Roman", serif' },
      { name: "--font-size-xx-small", value: "0.625rem" },
      { name: "--font-size-x-small", value: "0.75rem" },
      { name: "--font-size-small", value: "0.875rem" },
      { name: "--font-size-medium", value: "1rem" },
      { name: "--font-size-large", value: "1.25rem" },
      { name: "--font-size-x-large", value: "1.5rem" },
      { name: "--font-size-xx-large", value: "2.25rem" },
      { name: "--font-size-xxx-large", value: "3rem" },
      { name: "--font-size-xxxx-large", value: "4.5rem" },
      { name: "--font-weight-light", value: "300" },
      { name: "--font-weight-normal", value: "400" },
      { name: "--font-weight-semibold", value: "500" },
      { name: "--font-weight-bold", value: "700" },
      { name: "--letter-spacing-dense", value: "-0.015em" },
      { name: "--letter-spacing-normal", value: "normal" },
      { name: "--letter-spacing-loose", value: "0.075em" },
      { name: "--line-height-dense", value: "1.4" },
      { name: "--line-height-normal", value: "1.8" },
      { name: "--line-height-loose", value: "2.2" },
    ],
  },
];

export default vars;
